10 REM INSTALL MUSIC PLAYER FOR &
20 PRINT CHR$(4);"BRUN PLAY.BIN"
25 PRINT:PRINT "RUN A BASIC PROGRAM TO HEAR"
27 PRINT "THE MUSIC PLAYER IN ACTION!":PRINT
30 REM CATALOG THE FILESYSTEM
40 PRINT CHR$(4);"CATALOG"
