10 REM INSTALL MUSIC PLAYER FOR &
20 PRINT CHR$(4);"BLOAD PLAY.BIN"
22 CALL 32768
25 PRINT:PRINT "RUN A BASIC PROGRAM TO HEAR"
27 PRINT "THE MUSIC PLAYER IN ACTION!":PRINT
30 REM CATALOG THE FILESYSTEM
40 REMPRINT CHR$(4);"CATALOG"
